// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5-pGFzcryhFlFllUd6ah2p_QAmvj1wLU',
    appId: '1:646008175948:web:0e1490ef9e107ee60f23e9',
    messagingSenderId: '646008175948',
    projectId: 'tunehop-b74c9',
    authDomain: 'tunehop-b74c9.firebaseapp.com',
    storageBucket: 'tunehop-b74c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc90Nta3OwZMgoBlBkVSUlAuGM49PNJyQ',
    appId: '1:646008175948:android:89fda26ee9714de20f23e9',
    messagingSenderId: '646008175948',
    projectId: 'tunehop-b74c9',
    storageBucket: 'tunehop-b74c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCALntnmBJrUlpFBcSxOndadXiUc4I4_iA',
    appId: '1:646008175948:ios:10dd2a01cbfbba2b0f23e9',
    messagingSenderId: '646008175948',
    projectId: 'tunehop-b74c9',
    storageBucket: 'tunehop-b74c9.appspot.com',
    iosClientId: '646008175948-3do37lbhp2nppvo2l0os0252f000dl22.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuneHopApp',
  );
}
